### ISSUE TITLE
panic: not a sharded connection

### ISSUE THREAD

**Issue by mrVanboy** [scylladb/gocql#10]
Sometime `github.com/gocql/gocql` panics in our environment from the unknown reason.

### What version of Scylla or Cassandra are you using?
ScyllaDB 2018.1.10

### What version of Gocql are you using?
/go/pkg/mod/github.com/scylladb/gocql@v1.0.0

### What did you do?
Typically we are scanning structs with many fields. But I'm not sure if it is related to any calls to the database.

### What did you expect to see?
No panic.

### What did you see instead?
```
panic: scylla: IP:PORT not a sharded connection

goroutine 791411 [running]:
github.com/gocql/gocql.(*scyllaConnPicker).Remove(0xc000745c80, 0xc0184fc360)
	/go/pkg/mod/github.com/scylladb/gocql@v1.0.0/scylla.go:110 +0x127
github.com/gocql/gocql.(*hostConnPool).HandleError(0xc0002442a0, 0xc0184fc360, 0x1036240, 0xc00aa2abe0, 0xc0309bce01)
	/go/pkg/mod/github.com/scylladb/gocql@v1.0.0/connectionpool.go:547 +0xa4
github.com/gocql/gocql.(*Conn).closeWithError(0xc0184fc360, 0x1036240, 0xc00aa2abe0)
	/go/pkg/mod/github.com/scylladb/gocql@v1.0.0/conn.go:469 +0x289
github.com/gocql/gocql.(*Conn).exec(0xc0184fc360, 0x104eb60, 0xc0087cb5c0, 0x1034e80, 0x1972c48, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/scylladb/gocql@v1.0.0/conn.go:823 +0x8b4
github.com/gocql/gocql.(*startupCoordinator).write(0xc01a810430, 0x104eb60, 0xc0087cb5c0, 0x1034e80, 0x1972c48, 0x8ea755, 0x101e6e3, 0x33, 0xc000cb8f48)
	/go/pkg/mod/github.com/scylladb/gocql@v1.0.0/conn.go:340 +0x188
github.com/gocql/gocql.(*startupCoordinator).options(0xc01a810430, 0x104eb60, 0xc0087cb5c0, 0x101e6e3, 0x33)
	/go/pkg/mod/github.com/scylladb/gocql@v1.0.0/conn.go:349 +0x75
github.com/gocql/gocql.(*startupCoordinator).setupConn.func2(0xc01a810430, 0x104eb60, 0xc0087cb5c0, 0xc00159dce0)
	/go/pkg/mod/github.com/scylladb/gocql@v1.0.0/conn.go:314 +0x8b
created by github.com/gocql/gocql.(*startupCoordinator).setupConn
	/go/pkg/mod/github.com/scylladb/gocql@v1.0.0/conn.go:312 +0xdf
```

**Comment by dahankzter** [comment]
Can you share a reproducible example? Something small we can try?

**Comment by mmatczuk** [comment]
@dahankzter the scenario is visible from the trace.

**Comment by dahankzter** [comment]
Oh yeah it's an options query. We should perhaps just be more forgiving here.
