### ISSUE TITLE
panic from `unmarshalDecimal`

### ISSUE THREAD

**Issue by dkropachev** [scylladb/gocql#116]
Stack:
```
Command error: panic: runtime error: slice bounds out of range [4:0]
goroutine 3241 [running]:
github.com/gocql/gocql.unmarshalDecimal(0xceb600, 0xc023cf7740, 0xc14610b0b7, 0x0, 0x2c06f48, 0xbc1040, 0xc175aaa240, 0xc175aaa240, 0x16)
/home/penberg/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/marshal.go:1094 +0x495
github.com/gocql/gocql.Unmarshal(0xceb600, 0xc023cf7740, 0xc14610b0b7, 0x0, 0x2c06f48, 0xbc1040, 0xc175aaa240, 0x4ad253, 0xc00e81ed30)
/home/penberg/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/marshal.go:150 +0x3b6
github.com/gocql/gocql.unmarshalNullable(0xceb600, 0xc023cf7740, 0xc14610b0b7, 0x0, 0x2c06f48, 0xc010c493c0, 0xc23421fbf8, 0xc23421fbf8, 0x16)
/home/penberg/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/marshal.go:204 +0x219
github.com/gocql/gocql.Unmarshal(0xceb600, 0xc023cf7740, 0xc14610b0b7, 0x0, 0x2c06f48, 0xc010c493c0, 0xc23421fbf8, 0xc023cf7780, 0xc14610b0b3)
/home/penberg/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/marshal.go:127 +0xe5c
github.com/gocql/gocql.unmarshalMap(0xceb5c0, 0xc02b4a0900, 0xc14610b0b7, 0x7ee, 0x2c06f4c, 0xc00c179c80, 0xc2341cb378, 0xc02ec910aa, 0x8005b1)
/home/penberg/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/marshal.go:1662 +0x6e6
github.com/gocql/gocql.Unmarshal(0xceb5c0, 0xc02b4a0900, 0xc14610a9ff, 0xea6, 0x2c07600, 0xc00c179c80, 0xc2341cb378, 0x0, 0x0)
/home/penberg/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/marshal.go:158 +0xcbf
github.com/gocql/gocql.scanColumn(0xc14610a9ff, 0xea6, 0x2c07600, 0xc02d0c786c, 0x3, 0xc02d0c7870, 0x6, 0xc02d0c7878, 0x4, 0xceb5c0, ...)
/home/penberg/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/session.go:1346 +0x274
github.com/gocql/gocql.(*Iter).Scan(0xc04b4487e0, 0xc0ec293ba0, 0xf, 0x1a, 0x1197e40)
/home/penberg/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/session.go:1446 +0x2e5
github.com/gocql/gocql.(*Iter).MapScan(0xc04b4487e0, 0xc1757f2ab0, 0x1401)
```

Peace of unsafe code:
```
func unmarshalDecimal(info TypeInfo, data []byte, value interface{}) error {
	switch v := value.(type) {
	case Unmarshaler:
		return v.UnmarshalCQL(info, data)
	case *inf.Dec:
		scale := decInt(data[0:4])
		unscaled := decBigInt2C(data[4:], nil)
		*v = *inf.NewDecBig(unscaled, inf.Scale(scale))
		return nil
	}
	return unmarshalErrorf("can not unmarshal %s into %T", info, value)
}
```

**Comment by dkropachev** [comment]
This issue to be addressed on the upstream - https://github.com/gocql/gocql/issues/1693
