### ISSUE TITLE
When adding a new datacenter with a replication factor of 0, the GoCQL client hard-faults.

### ISSUE THREAD

**Issue by Snipa22** [scylladb/gocql#71]
### What version of Scylla or Cassandra are you using?
2020.1.3-0.20201001.6bab5d934b

### What version of Gocql are you using?
1.4.0

### What did you do?
Added a new datacenter with a replication factor of 0 to the keyspace via:
```
ALTER KEYSPACE parler WITH replication = { 'class' : 'NetworkTopologyStrategy', 'us-west-2-ent' : 3, 'us-west-2-ent-b' : 0 } AND durable_writes = true;
```

### What did you expect to see?
No errors occouring

### What did you see instead?
```
panic: invalid replication_factor 0. Is the "parler:dc=us-west-2-ent-b" keyspace configured correctly?

goroutine 1 [running]:
github.com/gocql/gocql.getReplicationFactorFromOpts(0xc0027cb940, 0x19, 0x1779820, 0xc001f7e740, 0x4)
	/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/topology.go:63 +0x28d
github.com/gocql/gocql.getStrategy(0xc0018c4540, 0x6, 0xc0018c4540)
	/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/topology.go:82 +0x1e8
github.com/gocql/gocql.(*tokenAwareHostPolicy).updateReplicas(0xc0001d3260, 0xc001f7e6a0, 0x1ad61ce, 0x6)
	/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/policies.go:454 +0x230
github.com/gocql/gocql.(*tokenAwareHostPolicy).KeyspaceChanged(0xc0001d3260, 0x1ad61ce, 0x6, 0x0, 0x0)
	/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/policies.go:442 +0x99
github.com/gocql/gocql.(*Session).init(0xc0001d8000, 0xc000de0500, 0x0)
	/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/session.go:280 +0x5e4
github.com/gocql/gocql.NewSession(0xc000de0480, 0x5, 0x8, 0x1ad3e4f, 0x5, 0x0, 0x12a05f200, 0x23c34600, 0x2352, 0x1ad61ce, ...)
	/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/session.go:166 +0x809
github.com/gocql/gocql.(*ClusterConfig).CreateSession(...)
	/go/pkg/mod/github.com/scylladb/gocql@v1.4.0/cluster.go:194
gitlab.parler.com/server/server/support/goLibrary/helpers.initCassandra(0x1ad61ce, 0x6, 0x1ad5b0e)
	/builder/support/goLibrary/helpers/ctx.go:124 +0x585
gitlab.parler.com/server/server/support/goLibrary/helpers.InitCTX(0xc00087ea00, 0x1ea4de0, 0xc000554270, 0xc0005e2de0, 0xc000568780, 0xc000230050, 0xc0000b4140, 0xc000139540, 0x1e95120, 0x2a60db0, ...)
	/builder/support/goLibrary/helpers/ctx.go:212 +0x352
main.main()
	/builder/applications/golang/taskrunner/main.go:200 +0xfee

```
---

If you are having connectivity related issues please share the following additional information

### Describe your Cassandra cluster
please provide the following information

- output of `nodetool status`
```
nodetool status
Datacenter: us-west-2-ent
=========================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens       Owns    Host ID                               Rack
UN  10.3.33.195  3.5 TB     256          ?       31dcee36-27a1-4821-bc44-11a0f8dd3df5  2a
UN  10.3.33.107  4.13 TB    256          ?       c7f8d883-24c4-4070-a370-43e524a75270  2a
UN  10.3.33.138  3.23 TB    256          ?       1101667a-e0cb-4b44-9ba8-fe61592ee219  2a
UN  10.3.33.143  3.77 TB    256          ?       86505452-ca58-4a49-bb5a-9ce6a7adf2a2  2a
UN  10.3.33.140  3.77 TB    256          ?       8b2128d7-4c3f-4f94-89fe-82267a79f212  2a
UN  10.3.33.17   3.46 TB    256          ?       817fcb54-d5bd-4021-bc7d-f2df0f356833  2a
UN  10.3.33.86   3.71 TB    256          ?       c34a8838-3703-4699-9657-1ba20ae7fc26  2a
UN  10.3.33.246  3.79 TB    256          ?       26c0a6c6-6c8f-457f-aff1-1145b62406f9  2a
UN  10.3.33.118  4.58 TB    256          ?       41d9a5d0-0a79-4363-9100-7d3cbc23f2bb  2a
UN  10.3.33.245  1.56 TB    256          ?       0c36858f-e3c0-4f92-a945-a4ae50de46ec  2a
UN  10.3.33.20   3.76 TB    256          ?       0cfa3c08-b779-4e64-9ed9-5a03881f393f  2a
UN  10.3.33.59   1.58 TB    256          ?       90638e06-f4f0-46f4-8448-2ff7cbb5d44b  2a
UN  10.3.33.217  3.5 TB     256          ?       e386098a-be8a-4dbb-93ce-048c7c420c58  2a
UN  10.3.33.158  3.82 TB    256          ?       f2d25c53-c449-4d7f-97c0-8b5165005ed1  2a
UN  10.3.33.94   1.88 TB    256          ?       1add2664-57ab-45bc-a8b6-4022f08ac749  2a
UN  10.3.33.30   3.36 TB    256          ?       d3c2306a-567e-462e-b61e-b446b1c4de5b  2a
UN  10.3.33.189  3.89 TB    256          ?       880f82ac-c7f5-4d0d-a120-12632ef9b0fa  2a
UN  10.3.33.29   3.04 TB    256          ?       5b2dbd33-fae9-4c19-a55b-2101db237879  2a
UN  10.3.33.156  3.87 TB    256          ?       417dc5af-20fd-4e97-b564-9ddf3f11d125  2a
UN  10.3.33.188  2.9 TB     256          ?       8ca80c8f-2c8b-4070-a993-dd9bcaeeea15  2a

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```
- output of `SELECT peer, rpc_address FROM system.peers`
```
cqlsh> SELECT peer, rpc_address FROM system.peers;

 peer        | rpc_address
-------------+-------------
 10.3.33.189 | 10.3.33.189
  10.3.33.86 |  10.3.33.86
 10.3.33.118 | 10.3.33.118
  10.3.33.29 |  10.3.33.29
 10.3.33.138 | 10.3.33.138
 10.3.33.245 | 10.3.33.245
  10.3.33.17 |  10.3.33.17
 10.3.33.140 | 10.3.33.140
  10.3.33.20 |  10.3.33.20
 10.3.33.156 | 10.3.33.156
  10.3.33.94 |  10.3.33.94
  10.3.33.59 |  10.3.33.59
 10.3.33.188 | 10.3.33.188
 10.3.33.246 | 10.3.33.246
  10.3.33.30 |  10.3.33.30
 10.3.33.195 | 10.3.33.195
 10.3.33.143 | 10.3.33.143
 10.3.33.217 | 10.3.33.217
 10.3.33.158 | 10.3.33.158
```
- rebuild your application with the `gocql_debug` tag and post the output

Note: This functionally appears to be a bug where a RF of 0 is considered to be a hard-fault in the gocql client.

**Comment by martin-sucha** [comment]
This is tracked upstream at https://github.com/gocql/gocql/issues/1388

**Comment by Fornax96** [comment]
This is especially harmful since the official documentation actually says that setting a replication factor of 0 is required for adding a new DC to a cluster:

https://docs.scylladb.com/operating-scylla/procedures/cluster-management/add_dc_to_existing_dc/

I just did that and all my gocql clients crashed simultaneously!
