### ISSUE TITLE
Panic in query_executor

### ISSUE THREAD

**Issue by jefftt** [scylladb/gocql#88]
Please answer these questions before submitting your issue. Thanks!

### What version of Scylla or Cassandra are you using?
Scylla Enterprise 2021.1.4 

### What version of Gocql are you using?
`v0.0.0-20210215130051-390af0fb2915`

### What version of Go are you using?
1.15

### What did you do?
Cluster repair

### What did you expect to see?
No panic

### What did you see instead?
panic
---

A cluster repair triggered a panic with the stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf6ff26]

goroutine 35151517 [running]:
github.com/gocql/gocql.(*queryMetrics).attempt(0x0, 0x1, 0x60a1fd2, 0xc000313380, 0x7f536f095f00, 0x2573040, 0x60a1fd2)
        /vendor/github.com/gocql/gocql/session.go:808 +0x26
github.com/gocql/gocql.(*Query).attempt(0xc0049c2900, 0xc0000360b6, 0x8, 0xc0556659e3f166f3, 0x7f5375137f20, 0x2573040, 0xc0556659dde74724, 0x7f536f095f4e, 0x2573040, 0xc004a84c60, ...)
        /vendor/github.com/gocql/gocql/session.go:1049 +0xca
github.com/gocql/gocql.(*queryExecutor).attemptQuery(0xc000799b80, 0x1aab860, 0xc0063614c0, 0x1aba0c0, 0xc0049c2900, 0xc000fac900, 0xc0000516f8)
        /vendor/github.com/gocql/gocql/query_executor.go:35 +0x123
github.com/gocql/gocql.(*queryExecutor).do(0xc000799b80, 0x1aab860, 0xc0063614c0, 0x1aba0c0, 0xc0049c2900, 0xc0049a8e80, 0x184b170)
        /vendor/github.com/gocql/gocql/query_executor.go:127 +0x1b3
github.com/gocql/gocql.(*queryExecutor).run(0xc000799b80, 0x1aab860, 0xc0063614c0, 0x1aba0c0, 0xc0049c2900, 0xc0049a8e80, 0xc0032db3e0)
        /vendor/github.com/gocql/gocql/query_executor.go:173 +0x85
created by github.com/gocql/gocql.(*queryExecutor).executeQuery
       /vendor/github.com/gocql/gocql/query_executor.go:85 +0x2ea
```

Unfortunately since this only happened during a repair, cannot get a reproducible program.

We suspect it may have something to do with either retry policy or speculative execution, our usage is like so:
```
var (
	speculativeExecPolicy = gocql.SimpleSpeculativeExecution{
		NumAttempts:  2,
		TimeoutDelay: 100 * time.Millisecond,
	}

	retryPolicy = gocql.ExponentialBackoffRetryPolicy{
		NumRetries: 2,
		Min:        10 * time.Millisecond,
	}
)


func queryWithRetry(...) {
	ttl := qb.TTL(...)
	query := dbSession.
		Query(
			table.InsertBuilder().
				TTLNamed("ttl").
				ToCql(),
		).
		Consistency(consistency).
		RetryPolicy(&retryPolicy).
		BindStructMap(obj, qb.M{"ttl": ttl})

	err = query.ExecRelease()
}

func queryWithSpeculativeExecution(...) {
	query := qb.Select("table").
		Where(qb.Eq("id")).
		CountAll().
		Query(dbSession).
		Consistency(gocql.LocalOne).
		SetSpeculativeExecutionPolicy(&speculativeExecPolicy).
		Bind(id)

	var count int
	return query.GetRelease(&count)

}
```

**Comment by jefftt** [comment]
@martin-sucha think we can close this now as it is a dupe of https://github.com/gocql/gocql/issues/1315 AFAICT
